import * as Image from "../Assets/Product_images/index";

const data3D = [
  {
    id: 1,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2012,
    quantity: 1,
    img: Image.img28,
  },
  {
    id: 2,
    artist: "Ben",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2012,
    quantity: 1,
    img: Image.img22,
  },
  {
    id: 3,
    artist: "Julie",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2015,
    quantity: 1,
    img: Image.img13,
  },
  {
    id: 4,
    artist: "Jon",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2016,
    quantity: 1,
    img: Image.img19,
  },
  {
    id: 5,
    artist: "Sara",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img25,
  },
  {
    id: 6,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2017,
    quantity: 1,
    img: Image.img26,
  },
  {
    id: 7,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img27,
  },
  {
    id: 8,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img28,
  },
  {
    id: 9,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img10,
  },
  {
    id: 10,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img12,
  },
  {
    id: 11,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img11,
  },
  {
    id: 12,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img15,
  },
  {
    id: 13,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img17,
  },
  {
    id: 14,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img16,
  },
  {
    id: 15,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img1,
  },
  {
    id: 16,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img2,
  },
  {
    id: 17,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img1,
  },
  {
    id: 18,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img8,
  },
  {
    id: 19,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img9,
  },
  {
    id: 20,
    artist: "John",
    price: 101,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img3,
  },
];

export default data3D;
