import * as Image from "../Assets/Product_images/index";

const artdata = [
  {
    id: 21,
    artist: "John",
    price: 150,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2012,
    quantity: 1,
    img: Image.img1,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 22,
    artist: "Ben",
    price: 115,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2012,
    quantity: 1,
    img: Image.img2,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 23,
    artist: "Julie",
    price: 130,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2015,
    quantity: 1,
    img: Image.img3,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 24,
    artist: "Jon",
    price: 180,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2016,
    quantity: 1,
    img: Image.img4,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 25,
    artist: "Sara",
    price: 190,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img5,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 26,
    artist: "John",
    price: 120,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2017,
    quantity: 1,
    img: Image.img6,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 27,
    artist: "John",
    price: 80,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img7,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 28,
    artist: "John",
    price: 107,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img8,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 29,
    artist: "John",
    price: 99,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img9,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 30,
    artist: "John",
    price: 100,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img10,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 31,
    artist: "John",
    price: 200,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img11,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 32,
    artist: "John",
    price: 30,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img12,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 33,
    artist: "John",
    price: 130,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img13,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 34,
    artist: "John",
    price: 160,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img14,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 35,
    artist: "John",
    price: 170,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img15,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 36,
    artist: "John",
    price: 80,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img16,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 37,
    artist: "John",
    price: 58,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img17,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 38,
    artist: "John",
    price: 55,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img18,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 39,
    artist: "John",
    price: 87,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img19,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 40,
    artist: "John",
    price: 78,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img20,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
];

export default artdata;
