import * as Image from "../Assets/Product_images/index";
import * as Artist from "../Assets/artist-data/index";

const artdata = [
  {
    id: 21,
    artist: "Sample 1",
    price: 150,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2012,
    quantity: 1,
    img: Artist.Sample_1,
    description:
      "My work has always been a study into the human experience and how consciousness projects itself in our realities. It dives into topics we aim to distract ourselves from during the day, but we all face them when the absurdities of society fall pale in comparison to the genuine experiences of life. I tend to use vivid colors on purpose to promote the distraction we aim to create constantly but all the subjects after the first glance are real emotions faced by every individual in moments of silence and contemplation. ",
  },
  {
    id: 22,
    artist: "Sample 2",
    price: 115,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2012,
    quantity: 1,
    img: Artist.Sample_2,
    description:
      "My work has always been a study into the human experience and how consciousness projects itself in our realities. It dives into topics we aim to distract ourselves from during the day, but we all face them when the absurdities of society fall pale in comparison to the genuine experiences of life. I tend to use vivid colors on purpose to promote the distraction we aim to create constantly but all the subjects after the first glance are real emotions faced by every individual in moments of silence and contemplation. ",
  },
  {
    id: 23,
    artist: "Sample 3",
    price: 130,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2015,
    quantity: 1,
    img: Artist.Sample_3,
    description:
      "My work has always been a study into the human experience and how consciousness projects itself in our realities. It dives into topics we aim to distract ourselves from during the day, but we all face them when the absurdities of society fall pale in comparison to the genuine experiences of life. I tend to use vivid colors on purpose to promote the distraction we aim to create constantly but all the subjects after the first glance are real emotions faced by every individual in moments of silence and contemplation. ",
  },
  {
    id: 24,
    artist: "Sample 4",
    price: 180,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2016,
    quantity: 1,
    img: Artist.Sample_4,
    description:
      "My work has always been a study into the human experience and how consciousness projects itself in our realities. It dives into topics we aim to distract ourselves from during the day, but we all face them when the absurdities of society fall pale in comparison to the genuine experiences of life. I tend to use vivid colors on purpose to promote the distraction we aim to create constantly but all the subjects after the first glance are real emotions faced by every individual in moments of silence and contemplation. ",
  },
  {
    id: 25,
    artist: "Maria Tabet-A friend-Acrylic",
    price: 190,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Artist.img5,
    description:
      "My work has always been a study into the human experience and how consciousness projects itself in our realities. It dives into topics we aim to distract ourselves from during the day, but we all face them when the absurdities of society fall pale in comparison to the genuine experiences of life. I tend to use vivid colors on purpose to promote the distraction we aim to create constantly but all the subjects after the first glance are real emotions faced by every individual in moments of silence and contemplation. ",
  },
  {
    id: 26,
    artist: "Maria Tabet-Dinner etiquette- Acrylic",
    price: 120,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2017,
    quantity: 1,
    img: Artist.img6,
    description:
      "My work has always been a study into the human experience and how consciousness projects itself in our realities. It dives into topics we aim to distract ourselves from during the day, but we all face them when the absurdities of society fall pale in comparison to the genuine experiences of life. I tend to use vivid colors on purpose to promote the distraction we aim to create constantly but all the subjects after the first glance are real emotions faced by every individual in moments of silence and contemplation. ",
  },
  {
    id: 27,
    artist: "Maria Tabet- Monday evening- acrylic",
    price: 80,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Artist.img7,
    description:
      "My work has always been a study into the human experience and how consciousness projects itself in our realities. It dives into topics we aim to distract ourselves from during the day, but we all face them when the absurdities of society fall pale in comparison to the genuine experiences of life. I tend to use vivid colors on purpose to promote the distraction we aim to create constantly but all the subjects after the first glance are real emotions faced by every individual in moments of silence and contemplation. ",
  },
  {
    id: 28,
    artist: "Maria G.",
    price: 107,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img8,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 29,
    artist: "Maria G.",
    price: 99,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img9,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 30,
    artist: "Maria G.",
    price: 100,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img10,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 31,
    artist: "Maria G.",
    price: 200,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img11,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 32,
    artist: "Maria G.",
    price: 30,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img12,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 33,
    artist: "Maria G.",
    price: 130,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img13,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 34,
    artist: "Maria G.",
    price: 160,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img14,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 35,
    artist: "Maria G.",
    price: 170,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img15,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 36,
    artist: "Maria G.",
    price: 80,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img16,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 37,
    artist: "Maria G.",
    price: 58,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img17,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 38,
    artist: "Maria G.",
    price: 55,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img18,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 39,
    artist: "Maria G.",
    price: 87,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img19,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
  {
    id: 40,
    artist: "Maria G.",
    price: 78,
    material: "Paints",
    technique: "Latin",
    dimension: "Classic",
    year: 2019,
    quantity: 1,
    img: Image.img20,
    description:
      "Painter ELON MUSK’s work was recently featured in New American Paintings #146 curated by New York Magazine's Jerry Saltz. Additional features include Architectural Digest, ArtMaze, and Vice / Garage. Elrod is co-director of the artist-run gallery Underdonk in New York, and co-curated at Heliopolis Gallery from 2012-2015.",
  },
];

export default artdata;
